default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", 'localhost') %>
  user: <%= ENV.fetch("DB_USER", 'postgres') %>
  password: <%= ENV.fetch("DB_PASSWORD", 'password') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: parker_development

test:
  <<: *default
  database: parker_test

production:
  <<: *default
  database: parker_production
